apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-configuration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Thang2005HCMUS/TestYas.git
    path: k8s/charts/yas-configuration
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: yas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true