backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-inventory
    tag: e91d692

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: true
