backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-inventory
    tag: 82d3d65

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: true
