backend:
  image:
    repository: ghcr.io/thang2005hcmus/yas-search
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
