backend:
  image:
    repository: ghcr.io/thang2005hcmus/yas-promotion
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
