ui:
  image:
    repository: ghcr.io/nashtech-garage/yas-backoffice
    tag: latest
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: true
    host: backoffice.yas.local.com  # Thay bằng domain của bạn
    path: /
    pathType: ImplementationSpecific