ui:
  image:
    repository: ghcr.io/thang2005hcmus/yas-backoffice
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: false