backend:
  image:
    repository: ghcr.io/thang2005hcmus/yas-recommendation
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6

  nameOverride: recommendation
  fullnameOverride: recommendation
  databaseName: recommendation
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-openai-api-key-secret
  extraVolumes:
    - name: recommendation-application
      configMap:
        name: recommendation-application-configmap
  extraVolumeMounts:
    - name: recommendation-application
      mountPath: /opt/yas/recommendation
  extraApplicationConfigPaths:
    - /opt/yas/recommendation/recommendation-application.yaml
