backend:
  image:
    repository: ghcr.io/thang2005hcmus/yas-location
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6

  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: false
