apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: yas-default-deny
  namespace: yas
spec: {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-health-checks
  namespace: yas
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET"]
            paths:
              - /actuator/health
              - /actuator/health/*
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-product-callers
  namespace: yas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas/sa/cart
              - cluster.local/ns/yas/sa/order
              - cluster.local/ns/yas/sa/mesh-curl-allowed
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-cart-callers
  namespace: yas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas/sa/order
              - cluster.local/ns/yas/sa/mesh-curl-allowed
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-tax-callers
  namespace: yas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tax
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas/sa/order
              - cluster.local/ns/yas/sa/mesh-curl-allowed
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-order-callers
  namespace: yas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas/sa/mesh-curl-allowed
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-yas-fault-callers
  namespace: yas
spec:
  selector:
    matchLabels:
      app: yas-fault
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas/sa/mesh-curl-allowed
