backend:
  image:
    repository: ghcr.io/thang2005hcmus/yas-payment
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6

  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap
  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/yas/payment
  extraApplicationConfigPaths:
    - /opt/yas/payment/payment-application.yaml