backend:
  image:
    repository: ghcr.io/thang2005hcmus/yas-media
    tag: sha-d48fc80f3319c2159c215370fe5d6b8521687fc6

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

