opentelemetryCollectorConfig:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    loki:
      protocols:
        http:
          endpoint: 0.0.0.0:3500
      use_incoming_timestamp: true
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 80
      spike_limit_percentage: 20
    batch: {}
    attributes:
      actions:
        - action: insert
          key: loki.attribute.labels
          value: namespace,container,pod,level,traceId
        - action: insert
          key: loki.format
          value: raw

  exporters:
    loki:
      endpoint: http://loki-gateway/loki/api/v1/push
    otlphttp:
      endpoint: http://tempo:4318
  service:
    extensions: [health_check]
    pipelines:
      logs:
        receivers: [loki]
        processors: [memory_limiter, attributes, batch]
        exporters: [loki]
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlphttp]
