backend:
  image:
    repository: docker.io/23122051/yas-customer
    tag: e91d692

  nameOverride: customer
  fullnameOverride: customer
  databaseName: customer
  ingress:
    enabled: true
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/yas/customer
  extraApplicationConfigPaths:
    - /opt/yas/customer/customer-application.yaml
