name: customer service ci

on:
  push:
    branches: ["**"]
    paths:
      - "customer/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/customer-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "customer/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/customer-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions
      - name: Detect Service Name
        run: |
          FILE="${GITHUB_WORKFLOW_REF##*/}"
          FILE="${FILE%@*}"              # sampledata-ci.yaml
          SERVICE="${FILE%-ci.yaml}"    # sampledata

          echo "SERVICE_NAME=$SERVICE" >> $GITHUB_ENV
      - name: Run Maven Build Command
        run: mvn clean install -pl customer -am
      - name: Run Maven Checkstyle
        
        run: mvn checkstyle:checkstyle -pl customer -am -Dcheckstyle.output.file=customer-checkstyle-result.xml
      - name: Upload Checkstyle Result
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/customer-checkstyle-result.xml'
      - name: Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Customer-Service-Unit-Test-Results
          path: "customer/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: Analyze with sonar cloud
        id: sonar
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -pl customer -am -f pom.xml
          -Dsonar.coverage.jacoco.xmlReportPaths=customer/target/site/jacoco/jacoco.xml

      - name: SonarCloud Summary
        if: always()
        run: |
          if [ "${{ steps.sonar.outcome }}" = "success" ]; then
            ICON="🟢"
            STATUS="PASS"
          else
            ICON="🔴"
            STATUS="FAIL"
          fi

          {
            echo "## SonarCloud Report"
            echo ""
            echo "| Item | Value |"
            echo "|------|-------|"
            echo "| Status | $ICON **$STATUS** |"
            echo "| Raw Outcome | \`${{ steps.sonar.outcome }}\` |"
            echo "| Final Conclusion | \`${{ steps.sonar.conclusion }}\` |"
            echo "| Service | \`${{ env.SERVICE_NAME }}\` |"
            echo "| Branch | \`${{ github.ref_name }}\` |"
            echo "| Commit | \`${{ github.sha }}\` |"
            echo "| Actor | \`${{ github.actor }}\` |"
            echo ""
            echo "### Dashboard"
            echo "https://sonarcloud.io/dashboard?id=<YOUR_PROJECT_KEY>"
            echo ""
            echo "### Notes"
            echo "- If status = FAIL, open Sonar step logs."
            echo "- Check Quality Gate, coverage, bugs, vulnerabilities."
            echo "- If using continue-on-error, workflow still continues."
          } >> $GITHUB_STEP_SUMMARY
      - name: OWASP Dependency Check
        
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'yas'
          path: '.'
          format: 'HTML'
      - name: Upload OWASP Dependency Check results
        
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        
        with:
          paths: ${{github.workspace}}/customer/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
          title: 'Customer Coverage Report'
          update-comment: true
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./customer
          push: true
          tags: ghcr.io/nashtech-garage/yas-customer:latest