name: storefront service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "storefront/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/storefront-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "storefront/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/storefront-ci.yaml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: storefront
      - run: npm run build
        working-directory: storefront
      - run: npm run lint
        working-directory: storefront
      - run: npx prettier --check .
        working-directory: storefront
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        with:
          projectBaseDir: storefront
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Summary
        if: always()
        run: |
          if [ "${{ steps.sonar.outcome }}" = "success" ]; then
            ICON="🟢"
            STATUS="PASS"
          else
            ICON="🔴"
            STATUS="FAIL"
          fi

          {
            echo "## SonarCloud Report"
            echo ""
            echo "| Item | Value |"
            echo "|------|-------|"
            echo "| Status | $ICON **$STATUS** |"
            echo "| Raw Outcome | \`${{ steps.sonar.outcome }}\` |"
            echo "| Final Conclusion | \`${{ steps.sonar.conclusion }}\` |"
            echo "| Service | \`cart\` |"
            echo "| Branch | \`${{ github.ref_name }}\` |"
            echo "| Commit | \`${{ github.sha }}\` |"
            echo "| Actor | \`${{ github.actor }}\` |"
            echo ""
            echo "### Dashboard"
            echo "https://sonarcloud.io/dashboard?id=<YOUR_PROJECT_KEY>"
            echo ""
            echo "### Notes"
            echo "- If status = FAIL, open Sonar step logs."
            echo "- Check Quality Gate, coverage, bugs, vulnerabilities."
            echo "- If using continue-on-error, workflow still continues."
          } >> $GITHUB_STEP_SUMMARY
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./storefront
          push: true
          tags: ghcr.io/nashtech-garage/yas-storefront:latest