name: CI Dashboard Summary

on:
  workflow_run:
    workflows: ["* service ci"] # Nghe tất cả các workflow có tên kết thúc bằng 'service ci'
    types:
      - completed

jobs:
  Summary:
    runs-on: ubuntu-latest
    steps:
      - name: Report Status
        run: |
          STATUS="${{{{ github.event.workflow_run.conclusion }}}}"
          WORKFLOW_NAME="${{{{ github.event.workflow_run.name }}}}"
          if [ "$STATUS" = "success" ]; then ICON="✅"; else ICON="❌"; fi
          
          echo "## Dashboard Cập Nhật: $WORKFLOW_NAME" >> $GITHUB_STEP_SUMMARY
          echo "| Service Workflow | Status | Run Number | Link |" >> $GITHUB_STEP_SUMMARY
          echo "|------------------|--------|------------|------|" >> $GITHUB_STEP_SUMMARY
          echo "| $WORKFLOW_NAME | $ICON $STATUS | ${{{{ github.event.workflow_run.run_number }}}} | [View](${{{{ github.event.workflow_run.html_url }}}}) |" >> $GITHUB_STEP_SUMMARY
          