backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-payment
    tag: v1.0.0

  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: true
  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap
  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/yas/payment
  extraApplicationConfigPaths:
    - /opt/yas/payment/payment-application.yaml